### ISSUE TITLE
Pending Issues for Week 1

### ISSUE THREAD

**Issue by HumphreyYang** [QuantEcon/workshop.africa-july2023#11]
Hi @HengchengZhang @shlff @Smit-create @chappiewuzefan @DiaPorntipa,

I created this issue to keep track of unfinished tasks and get everyone synced about changes that are going to be made : )

Please feel free to add/take over any pending tasks here.

**Comment by HumphreyYang** [comment]
- [x] Remove all the "summer" in the subtitle for consistency (completed by @Smit-create in #12)

**Comment by HumphreyYang** [comment]
- [ ] Use `# TODO: ... `  when input from students is required.

**Comment by HumphreyYang** [comment]
Review code and content of all exercises:

- [x] Day 1 (#13 )
- [x] Day 2 (https://github.com/QuantEcon/workshop.africa-july2023/pull/14)
- [x] Day 3 (https://github.com/QuantEcon/workshop.africa-july2023/pull/15)
- [x] Day 4 (https://github.com/QuantEcon/workshop.africa-july2023/pull/16)
- [x] Day 5 (https://github.com/QuantEcon/workshop.africa-july2023/pull/18)

Day 2 and day 4 are now in #23.

**Comment by Smit-create** [comment]
I have assigned the first 3 exercises to myself. Please let me know if you guys are busy, I can do the rest in the evening.

**Comment by Smit-create** [comment]
Hi team,
While reviewing the exercise, I suggest using the following workflow:
1. Please test all the format/code issues.
2. Check that each solution works without any error.
3. Clear output for both the exercise and solution notebook.

**Comment by HumphreyYang** [comment]
Many thanks @Smit-create. This sounds great!

I suggest we also check for misspellings and grammar : )

1. Please test all the format/code issues.
2. Check that each solution works without any errors.
3. Check spelling and grammar.
4. Clear output for both the exercise and solution notebook.

Please also check the difficulty of the exercises and consider breaking down the exercises if you think they are too difficult or need further explanation.

**Comment by HumphreyYang** [comment]
> I have assigned the first 3 exercises to myself. Please let me know if you guys are busy, I can do the rest in the evening.

I am on days 4-5 and we can cross-validate once I have these reviewed : )

**Comment by HumphreyYang** [comment]
Hi @jstac and @mmcky, 

Exercises for week one are ready now. Many thanks for everyone's hard work.

Many thanks in advance.
