### ISSUE TITLE
[exercise set 1] Move matplotlib import

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/workshop.africa-july2023#19]
@HumphreyYang @Smit-create This was missed in my comments for https://github.com/QuantEcon/workshop.africa-july2023/pull/13

This is an odd request as it violates the usual rule but I would like to move

```
import matplotlib.pylot as plt
```

down to when it is first used near the bottom of the notebook. 

Currently the `jupyterlite` wasm environment shows an error when you import `matplotlib` and I don't want that to be the first thing shown in the notebook on day 1. We will hopefully fix the technical issue before the tutorial time.

**Comment by HumphreyYang** [comment]
Many thank @mmcky, I will make this change.
