### ISSUE TITLE
Using `%matplotlib inline`

### ISSUE THREAD

**Issue by HengchengZhang** [QuantEcon/workshop.africa-july2023#2]
Hi @mmcky I think when migrating the exercises to this repo, we don't need the magic line `%matplotlib inline` anymore.

A discussion can be found at [here](https://stackoverflow.com/questions/57085287/why-dont-i-need-matplotlib-inline-in-my-jupyter-notebook), the main idea is that this feature is hardcoded in ipykernel to that it auto-select the backend for us in Jupyter Notebook.

**Comment by mmcky** [comment]
I agree @HengchengZhang
